---
name: Publish docker image

on:
  push:
    tags: "*"

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Python dependencies
        run: |
          pip install poetry
          poetry install
      - name: Run checks and tests
        run: |
          poetry run isort --recursive --diff
          poetry run black --check .
          poetry run flake8
          poetry run mypy
          poetry run pytest --cov --cov-fail-under=75
      - name: Build package
        run: poetry build
      - name: Publish package
        run: |
          poetry publish \
            --username=__token__ \
            --password=${{ secrets.PYPI_UPLOAD_TOKEN }}

  docker-publish:
    runs-on: ubuntu-latest
    needs: test-and-publish
    steps:
      - uses: actions/checkout@v2
      - name: Publish to GitHub packages
        uses: whoan/docker-build-with-cache-action@v2
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image_name: ${{ github.repository }}/yaml2jsonnet
